### Load required Libraries ###
require(lme4)
require(ggplot2)
require(plyr)
require(dplyr)
require(haven)
require(readxl)
require(ggpubr)
require(cowplot)
require(devtools)
require(glmmTMB)
require(bbmle)
require(boot)
require(pastecs)
require(pscl)
require(RMThreshold)
require(MASS)

options(digits = 3)
options(scipen = 999)